language: cpp
os: linux
dist: trusty
sudo: required
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq qtbase5-dev qt5-default cppcheck; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cppcheck qt5; fi
install:
- git clone --depth 1 https://github.com/fet-test/ci-build.git
script:
- ci-build/ci-build --fetdir ./ --fail-on-errors --code-analysis all --build
