language: cpp
dist: trusty
sudo: required
compiler:
- gcc
os:
- linux
before_install:
- sudo apt-get install -qq qtbase5-dev qt5-default cppcheck
script:
- cppcheck --enable=all src/engine src/interfaze
- qmake
- make
